apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    service: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-reverseproxy
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
      - image: oliveth96/reverseproxy:v1
        name: udagram-reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1000Mi"
            cpu: "250m"
          limits:
            memory: "2000Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always